# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftUI-UserLocation' do
  pod 'DTMHeatmap'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftUI-UserLocation

  target 'SwiftUI-UserLocationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftUI-UserLocationUITests' do
    # Pods for testing
  end

end
